#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
    enum WINMODE { MODE_FULL, MODE_WIN };

    // Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
    enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

    enum INFO { INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
    enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

    enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };
    enum IMGUITEXTUREID { TEX_TILE, TEX_WALL, TEX_OBJECT, TEX_MONSTER, IMGUITEX_END };

    enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_WALL, RENDER_UI, RENDER_UIALPHA, RENDER_WINDOW, RENDER_MAP, RENDER_SUBORDINATE, RENDER_END };

    enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
    enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

    enum STATE { IDLE, WALK, SWING, SHOOT, DEAD, STATE_END };

    enum DIRECTION { FRONT, RIGHT, BACK, LEFT, DIRECTION_END };

    enum RENDERTYPE { TYPE_PERSPECTIVE, TYPE_ORTHOGRAPHIC, TYPE_END };

    // 사운드 채널
    enum CHANNELID 
    { 
        SOUND_EFFECT, SOUND_IMPORTANT, SOUND_BGM, SOUND_INSTRUMENTS, 
        SOUND_PLAYER, SOUND_EAT, SOUND_FIRE, SOUND_PET,
        SOUND_SHAMAN, SOUND_MUSHROOM, SOUND_SLIME, SOUND_HUNTER,
        SOUND_PLANT, 
        
        MAXCHANNEL 
    };

    enum PROJECTILETYPE { ARROW, MAGIC, PROJECTILE_END };

    enum PLAYERHITTYPE { HIT_NORMAL, HIT_FIRE, HIT_ELECTRIC, HIT_BULLET, HIT_END };

    enum BUFFTYPE
    {
        BUFF_SPEED, BUFF_HP, BUFF_ATT, BUFF_DEF, BUFF_FULL, BUFF_IMMUNE, BUFF_MINING,
        DEBUFF_HUNGER, DEBUFF_FIRE, DEBUFF_SLOW, DEBUFF_STUN, BUFFTYPE_END
    };

    enum ITEMACTION { ACTION_SWING, ACTION_CHARGE, ACTION_INSTALL, ACTION_EAT, ACTION_END };

    // 아이템 고유값, 서로 다른 아이템이면 겹칠 수 없음
    // 장비는 50 이하의 값을 갖도록 설정하여 인벤토리에서 같은 아이템이어도 겹칠 수 없게 할 것
    enum ITEMNUM
    {
        // 도구
        ITEM_PICKAXE, ITEM_HOE, ITEM_WATERINGCAN,

        // 무기
        ITEM_SWORD = 10, ITEM_BOW, ITEM_STAFF,

        // 장비
        ITEM_HELMET = 20, ITEM_CHEST, ITEM_LEG,

        // 악세서리, 보조장비
        ITEM_NECKLACE = 30, ITEM_RING, ITEM_ASSISTANCE, ITEM_BAG, ITEM_LANTERN,

        // 오브젝트
        ITEM_TABLE = 40, ITEM_POTION_TABLE, ITEM_ACCESSORY_TABLE, ITEM_MUSIC_TABLE, ITEM_ANIMAL_TABLE,
        ITEM_ANVIL, ITEM_FURNACE, ITEM_COOKINGPOT,

        ITEM_ETC = 50,

        ITEM_PET,

        ITEM_TORCH, ITEM_BOX, ITEM_GRAVESTONE, ITEM_SPRINKLER,

        ITEM_POTION_HP, ITEM_POTION_ATT, ITEM_POTION_DEF,

        ITEM_BERRY, ITEM_PEPPER, ITEM_CARROT, ITEM_MUSHROOM,
        ITEM_BERRY_SEED, ITEM_PEPPER_SEED, ITEM_CARROT_SEED, ITEM_FIBER_SEED,

        ITEM_BERRY_BERRY_FOOD, ITEM_BERRY_PEPPER_FOOD, ITEM_BERRY_CARROT_FOOD, ITEM_BERRY_MUSHROOM_FOOD,
        ITEM_PEPPER_PEPPER_FOOD, ITEM_PEPPER_CARROT_FOOD, ITEM_PEPPER_MUSHROOM_FOOD,
        ITEM_CARROT_CARROT_FOOD, ITEM_CARROT_MUSHROOM_FOOD,
        ITEM_MUSHROOM_MUSHROOM_FOOD,
        ITEM_LUNCH, ITEM_CHOCOBAR,

        ITEM_PLAYER_SPAWNER, ITEM_MAL_SPAWNER, ITEM_AZEOS_SPAWNER,

        ITEM_SLIME_CORE, ITEM_LARVA_CORE, ITEM_MAL_CORE,
        
        ITEM_COPPER, ITEM_IRON, ITEM_SCARLET,
        ITEM_COPPER_BAR, ITEM_IRON_BAR, ITEM_SCARLET_BAR,
        ITEM_DIRTWALL, ITEM_STONEWALL, ITEM_GRASSWALL, ITEM_PASTUREWALL,
        ITEM_WOOD, ITEM_MUCUS, ITEM_FIBER, ITEM_SKULL_PIECE, ITEM_FEATHER_PIECE, ITEM_DIARY,
        
        ITEM_INSTRUMENT_HARP, ITEM_INSTRUMENT_CELLO, ITEM_INSTRUMENT_FLUTE, ITEM_INSTRUMENT_OCARINA, ITEM_INSTRUMENT_DRUM, ITEM_INSTRUMENT_PIANO,

        ITEM_END
    };

    enum MATERIAL { MATERIAL_WOOD, MATERIAL_COPPER, MATERIAL_IRON, MATERIAL_SCARLET, MATERIAL_SPECIAL, MATERIAL_END };

    enum MONSTERTYPE 
    { 
        MON_SLIME, MON_SHROOMMAN, 
        MON_SHAMAN,
        MON_HUNTER, MON_PROJECTILE, MON_BULLET,
        MON_MALUGAZ, MON_AZEOS, 
        MON_END 
    };

    enum ASSISTANCE { ASSISTANCE_WOOD_SHIELD, ASSISTANCE_FEATHER, ASSISTANCE_IRON_SHIELD, ASSISTANCE_AZEOS_FEATHER, ASSISTANCE_BOOK, ASSISTANCE_END };

    enum TABLETYPE{ TABLE_PLAYER, TABLE_CRAFT, TABLE_ANVIL, TABLE_ALCHEMY, TABLE_ACCESSORY, TABLE_MUSIC, TABLE_END };

    enum PLACEOBJECT { SLIME_FLOOR, MUSHROOM, AZEOS_POOP, AZEOS_FEATHER, MALGA_SUMMON, AZEOS_SUMMON, PLACEOBJ_END };
}
#endif // Engine_Enum_h__   
